---
include: https://raw.githubusercontent.com/hassio-addons/organization/master/gitlabci/addon.yml

variables:
  ADDON_GITHUB_REPO: "hassio-addons/addon-lutron-cert"
  ADDON_SLUG: "lutron-cert"
  ADDON_TARGET: "lutron-cert"

  ADDON_AARCH64_BASE: "hassioaddons/base-python-aarch64:5.3.2"
  ADDON_AMD64_BASE: "hassioaddons/base-python-amd64:5.3.2"
  ADDON_ARMHF_BASE: "hassioaddons/base-python-armhf:5.3.2"
  ADDON_ARMV7_BASE: "hassioaddons/base-python-armv7:5.3.2"
  ADDON_I386_BASE: "hassioaddons/base-python-i386:5.3.2"
